# Generated by Django 3.0.8 on 2020-08-22 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20200822_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='interests',
            new_name='interest1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='result',
        ),
        migrations.AddField(
            model_name='student',
            name='interest2',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='interest3',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
