# Generated by Django 3.0.8 on 2020-08-25 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20200824_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='network.Teacher'),
        ),
    ]
