# Generated by Django 3.0.8 on 2020-08-26 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20200825_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='network.Teacher'),
        ),
        migrations.CreateModel(
            name='QuizTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=10000000000000000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseer', to='network.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzzed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=100)),
                ('quiz', models.CharField(max_length=10000000000000000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursee', to='network.Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzz', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
