# Generated by Django 3.0.8 on 2020-08-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20200826_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='course',
            field=models.CharField(max_length=100),
        ),
    ]
