# Generated by Django 3.0.8 on 2020-08-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20200827_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='description_of_the_course',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
