# Generated by Django 3.0.8 on 2020-08-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20200827_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistered',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='courseregistered',
            name='student',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='courseregistered',
            name='teacher',
            field=models.CharField(max_length=100),
        ),
    ]
