# Generated by Django 3.0.8 on 2020-08-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='materials',
            field=models.FileField(upload_to='books/pdfs'),
        ),
    ]
