# Generated by Django 3.0.8 on 2020-08-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_auto_20200830_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('uploaded', models.FileField(upload_to='books/pdfs')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='materials',
            field=models.CharField(max_length=10000),
        ),
    ]
