# Generated by Django 3.0.8 on 2020-08-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_auto_20200830_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='category',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
