# Generated by Django 3.0.8 on 2020-08-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_teacher_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='course',
        ),
    ]
