# Generated by Django 3.0.8 on 2020-09-04 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0041_auto_20200902_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='quiztaken',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quiztaken',
            name='student',
        ),
        migrations.RemoveField(
            model_name='quiztaken',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursefers', to='network.Teacher'),
        ),
        migrations.AlterField(
            model_name='courseregistered',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='googlers', to='network.Teacher'),
        ),
        migrations.DeleteModel(
            name='AllPosts',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizTaken',
        ),
    ]
