# Generated by Django 3.0.8 on 2020-09-05 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0044_auto_20200905_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followed',
            name='followeds',
        ),
        migrations.RemoveField(
            model_name='followed',
            name='user',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='post',
        ),
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursefers', to='network.Teacher'),
        ),
        migrations.AlterField(
            model_name='courseregistered',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='googlers', to='network.Teacher'),
        ),
        migrations.DeleteModel(
            name='AllPosts',
        ),
        migrations.DeleteModel(
            name='followed',
        ),
        migrations.DeleteModel(
            name='likes',
        ),
    ]
